// Server-side campus configurations
// These merge over DEFAULT_TENANT when a campus is active via org-scoped URL
module.exports = {
  usc: {
    orgName: 'USC DART',
    orgShortName: 'DART',
    orgTagline: 'Disabled Access to Road Transportation',
    orgInitials: 'DT',
    primaryColor: '#990000',
    secondaryColor: '#FFCC00',
    secondaryTextColor: '#990000',
    sidebarBg: '#1A0000',
    sidebarText: '#C4A3A3',
    sidebarActiveBg: 'rgba(153,0,0,0.25)',
    sidebarHover: 'rgba(255,255,255,0.06)',
    sidebarBorder: 'rgba(255,255,255,0.08)',
    headerBg: '#FFE8A0',
    mapUrl: 'https://maps.usc.edu/',
    mapEmbeddable: true,
    mapTitle: 'USC Campus Map',
    campusKey: 'usc',
    locationsKey: 'usc',
    idFieldLabel: 'USC ID',
    idFieldMaxLength: 10,
    idFieldPattern: '^\\d{10}$',
    idFieldPlaceholder: '1234567890',
    serviceScopeText: 'USC campus only',
    timezone: 'America/Los_Angeles',
    rules: [
      'DART is a free service provided by USC Transportation to assist USC students, faculty and staff with mobility issues in getting around campus. Service is available at UPC during the Fall and Spring semesters only, between 8:00am\u20137:00pm, Monday\u2013Friday.',
      'DART vehicles (golf carts) are not city-street legal and cannot leave campus. Service is NOT available to off-campus housing, off-campus parking structures, the USC Village, etc.',
      'If the DART driver arrives at the pickup location and the rider is not present, the driver will wait up to 5 minutes (grace period). After 5 minutes, the ride will be marked as a no-show.',
      '5 consecutive no-shows will result in automatic service termination. Completed rides reset the no-show counter.',
      'Riders must be present at the designated pickup location at the requested time. The driver will not search the surrounding area.',
      'For safety reasons, DART carts follow designated campus paths and may not take the shortest route. Please allow extra time.'
    ],
  },
  stanford: {
    orgName: 'Stanford ATS',
    orgShortName: 'ATS',
    orgTagline: 'Accessible Transportation Service',
    orgInitials: 'AT',
    primaryColor: '#8C1515',
    secondaryColor: '#B6B1A9',
    secondaryTextColor: '#8C1515',
    sidebarBg: '#1A0505',
    sidebarText: '#C4A8A8',
    sidebarActiveBg: 'rgba(140,21,21,0.25)',
    sidebarHover: 'rgba(255,255,255,0.06)',
    sidebarBorder: 'rgba(255,255,255,0.08)',
    headerBg: '#EDE8E3',
    mapUrl: 'https://campus-map.stanford.edu/',
    mapEmbeddable: true,
    campusKey: 'stanford',
    locationsKey: 'stanford',
  },
  ucla: {
    orgName: 'UCLA BruinAccess',
    orgShortName: 'BruinAccess',
    orgTagline: 'Accessible Campus Transportation',
    orgInitials: 'BA',
    primaryColor: '#2774AE',
    secondaryColor: '#FFD100',
    secondaryTextColor: '#2774AE',
    sidebarBg: '#0D1B2A',
    sidebarText: '#8FAFC8',
    sidebarActiveBg: 'rgba(39,116,174,0.25)',
    sidebarHover: 'rgba(255,255,255,0.06)',
    sidebarBorder: 'rgba(255,255,255,0.08)',
    headerBg: '#C2DBFA',
    mapUrl: 'https://map.ucla.edu/',
    mapEmbeddable: true,
    campusKey: 'ucla',
    locationsKey: 'ucla',
  },
  uci: {
    orgName: 'UCI AnteaterExpress',
    orgShortName: 'AntExpress',
    orgTagline: 'Accessible Campus Transportation',
    orgInitials: 'AE',
    primaryColor: '#0064A4',
    secondaryColor: '#FFD200',
    secondaryTextColor: '#255799',
    sidebarBg: '#001A2E',
    sidebarText: '#7BAAC4',
    sidebarActiveBg: 'rgba(0,100,164,0.25)',
    sidebarHover: 'rgba(255,255,255,0.06)',
    sidebarBorder: 'rgba(255,255,255,0.08)',
    headerBg: '#D0DEF0',
    mapUrl: 'https://map.uci.edu/?id=463',
    mapEmbeddable: true,
    campusKey: 'uci',
    locationsKey: 'uci',
  },
  scranton: {
    orgName: 'Royal Ride',
    orgShortName: 'Royal Ride',
    orgTagline: 'University of Scranton Campus Transportation',
    orgInitials: 'RR',
    primaryColor: '#512D6D',
    secondaryColor: '#EA7A59',
    secondaryTextColor: '#512D6D',
    sidebarBg: '#1C1129',
    sidebarText: '#A99BC4',
    sidebarActiveBg: 'rgba(81,45,109,0.35)',
    sidebarHover: 'rgba(255,255,255,0.06)',
    sidebarBorder: 'rgba(255,255,255,0.08)',
    headerBg: '#EBE3F2',
    mapUrl: 'https://admissions.scranton.edu/our-campus/campus-maps.shtml',
    mapEmbeddable: false,
    mapTitle: 'University of Scranton Campus Map',
    campusKey: 'scranton',
    locationsKey: 'scranton',
    timezone: 'America/New_York',
    // Royal Rides serves off-campus addresses (hill section, downtown) —
    // enable Google Places address entry alongside campus buildings.
    addressAutocomplete: true,
    placesCenter: { lat: 41.4044, lng: -75.6552 }, // University of Scranton
    placesRadiusMeters: 8000,
  },
};

// All Pacific campuses share the USC timezone; keep every campus explicit so
// server-side validation never falls back to the host machine's clock.
for (const slug of ['stanford', 'ucla', 'uci']) {
  if (module.exports?.[slug] && !module.exports[slug].timezone) {
    module.exports[slug].timezone = 'America/Los_Angeles';
  }
}
