// Server-side campus configurations
// These merge over DEFAULT_TENANT when a campus is active via org-scoped URL
module.exports = {
  usc: {
    orgName: 'USC DART',
    orgShortName: 'DART',
    orgTagline: 'Disabled Access to Road Transportation',
    orgInitials: 'DT',
    primaryColor: '#990000',
    secondaryColor: '#FFCC00',
    secondaryTextColor: '#990000',
    sidebarBg: '#1A0000',
    sidebarText: '#C4A3A3',
    sidebarActiveBg: 'rgba(153,0,0,0.25)',
    sidebarHover: 'rgba(255,255,255,0.06)',
    sidebarBorder: 'rgba(255,255,255,0.08)',
    headerBg: '#FFE8A0',
    mapUrl: 'https://maps.usc.edu/',
    campusKey: 'usc',
    locationsKey: 'usc',
  },
  stanford: {
    orgName: 'Stanford ATS',
    orgShortName: 'ATS',
    orgTagline: 'Accessible Transportation Service',
    orgInitials: 'AT',
    primaryColor: '#8C1515',
    secondaryColor: '#B6B1A9',
    secondaryTextColor: '#8C1515',
    sidebarBg: '#1A0505',
    sidebarText: '#C4A8A8',
    sidebarActiveBg: 'rgba(140,21,21,0.25)',
    sidebarHover: 'rgba(255,255,255,0.06)',
    sidebarBorder: 'rgba(255,255,255,0.08)',
    headerBg: '#EDE8E3',
    mapUrl: 'https://campus-map.stanford.edu/',
    campusKey: 'stanford',
    locationsKey: 'stanford',
  },
  ucla: {
    orgName: 'UCLA BruinAccess',
    orgShortName: 'BruinAccess',
    orgTagline: 'Accessible Campus Transportation',
    orgInitials: 'BA',
    primaryColor: '#2774AE',
    secondaryColor: '#FFD100',
    secondaryTextColor: '#2774AE',
    sidebarBg: '#0D1B2A',
    sidebarText: '#8FAFC8',
    sidebarActiveBg: 'rgba(39,116,174,0.25)',
    sidebarHover: 'rgba(255,255,255,0.06)',
    sidebarBorder: 'rgba(255,255,255,0.08)',
    headerBg: '#C2DBFA',
    mapUrl: 'https://map.ucla.edu/',
    campusKey: 'ucla',
    locationsKey: 'ucla',
  },
  uci: {
    orgName: 'UCI AnteaterExpress',
    orgShortName: 'AntExpress',
    orgTagline: 'Accessible Campus Transportation',
    orgInitials: 'AE',
    primaryColor: '#0064A4',
    secondaryColor: '#FFD200',
    secondaryTextColor: '#255799',
    sidebarBg: '#001A2E',
    sidebarText: '#7BAAC4',
    sidebarActiveBg: 'rgba(0,100,164,0.25)',
    sidebarHover: 'rgba(255,255,255,0.06)',
    sidebarBorder: 'rgba(255,255,255,0.08)',
    headerBg: '#D0DEF0',
    mapUrl: 'https://map.uci.edu/',
    campusKey: 'uci',
    locationsKey: 'uci',
  },
};
